---
- name: Apply arch install scripts and setup
  hosts: all
  tasks:
  - name: Apply pacstrap
    command:
      cmd: 'pacstrap -K /mnt {{ basePackages }}'
      creates: /mnt/bin
  - name: Generate fstab
    command: 
      cmd: genfstab -U /mnt
    register: genfstab_out
  - name: Apply fstab
    lineinfile:
      path: /mnt/etc/fstab
      backup: true
      line: '{{ item }}' 
      state: present
    loop: '{{ genfstab_out.stdout_lines }}'
